# Build cycle

before_install: python setup.py build
install: python setup.py install
before_script: 
script: python check,py
after_sucess:
after_failure:
after_script:

# Other params

language: python
python:
- 2.6
- 2.7

branches:
  only:
  - master
  - /^v[0-9]+.[0-9]+.[0-9]+$

env:


